global:
  cluster_name: &cluster_name my_cluster.mydomain.com
  domain: &domain mydomain.com
  bucket: &bucket s3://kops-my_cluster.mydomain.com
  environment: &environment dev
  provider: aws
  aws:
    region: eu-west-1
    availabilityZones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
    vpc_id:
      filters:
        key: "tag:Name"
        value: "dev"
    subnets:
      filters:
        key: "tag:Name"
        value: "dev_private*"
    utility-subnets:
      filters:
        key: "tag:Name"
        value: "dev_public*"

kops:
  snippets:
    cluster: /tmp/cluster.conf.d
    node: /tmp/node.conf.d
    master: /tmp/master.conf.d
  name: *cluster_name
  state: *bucket
  node-count: 3
  node-size: "m5.large"
  master-size: "m5.large"
  master-count: 1
#  admin-access: 
#  api-loadbalancer-type: 
#  api-ssl-certificate: 
#  associate-public-ip: 
#  authorization: 
#  bastion: 
#  channel: 
#  cloud: 
#  cloud-labels: 
#  dns: 
#  dns-zone: 
#  dry-run: 
#  encrypt-etcd-storage: 
#  image: 
#  kubernetes-version: 
#  master-count: 
#  master-public-name: 
#  master-security-groups: 
#  master-size: 
#  master-tenancy: 
#  master-volume-size: 
#  master-zones: 
#  model: 
#  network-cidr: 
#  networking: 
#  node-count: 
#  node-security-groups: 
#  node-size: 
#  node-tenancy: 
#  node-volume-size: 
#  out: 
#  outout,: 
#  project: 
#  ssh-access: 
#  ssh-public-key: [file_path]
#  subnets: 
#  target: 
#  topology: 
#  utility-subnets: 
#  vpc: 
#  zones: 

kubectl:
  - name: heapster
    url: https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
  - name: kube-dashboard
    url: https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.8.3.yaml

exec:
  # sample running shell script
  - command: monitoring/install.sh
    env:
      - name: AWS_ZONE
        value: eu-west-1
  # another command but change directory before ejecting
  - command: ./my_command.sh
    rundir: /home/randomuser
    env:
      - name: CLUSTER_NAME
        value: *cluster_name

helm:
  repositories:
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
    - name: incubator
      url: http://storage.googleapis.com/kubernetes-charts-incubator

  helmDefaults:
    wait: true
    timeout: 600

# if you use env variables you MUST escape the line with '
  releases:
    - name: nginx-ingress
      namespace: ingress
      chart: stable/nginx-ingress
      values:
      - '{{ requiredEnv "PWD" }}/nginx-ingress/values.yaml'

