global:
  cluster_name: &cluster_name my_cluster.mydomain.com
  domain: &domain mydomain.com
  bucket: &bucket s3://kops-my_cluster.mydomain.com
  environment: &environment dev
  provider: aws
  aws:
    region: eu-west-1
    availabilityZones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
    vpc_id:
      filters:
        key: "tag:Name"
        value: "dev"
      hook: aws ec2 describe-vpcs --filter "Name=tag:Name,Values=dev" --query Vpcs[*].VpcId --output text
    subnets:
      filters:
        key: "tag:Name"
        value: "dev_private*"
      hook: aws ec2 describe-subnets --filter "Name=tag:Name,Values=dev_private*" --query Subnets[*].SubnetId

kops:
  name: *cluster_name
  state: *bucket
  node-count: 3
  node-size: "m5.large"
  master-size: "m5.large"
  master-count: 3
#  admin-access: 
#  api-loadbalancer-type: 
#  api-ssl-certificate: 
#  associate-public-ip: 
#  authorization: 
#  bastion: 
#  channel: 
#  cloud: 
#  cloud-labels: 
#  dns: 
#  dns-zone: 
#  dry-run: 
#  encrypt-etcd-storage: 
#  image: 
#  kubernetes-version: 
#  master-count: 
#  master-public-name: 
#  master-security-groups: 
#  master-size: 
#  master-tenancy: 
#  master-volume-size: 
#  master-zones: 
#  model: 
#  network-cidr: 
#  networking: 
#  node-count: 
#  node-security-groups: 
#  node-size: 
#  node-tenancy: 
#  node-volume-size: 
#  out: 
#  outout,: 
#  project: 
#  ssh-access: 
#  ssh-public-key: [file_path]
#  subnets: 
#  target: 
#  topology: 
#  utility-subnets: 
#  vpc: 
#  zones: 

kubectl:
  - name: heapster
    url: https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
    namespace: monitoring
  - name: kube-dashboard
    url: https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.8.3.yaml
    namespace: default

helm:
  repositories:
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
    - name: incubator
      url: http://storage.googleapis.com/kubernetes-charts-incubator

  helmDefaults:
    wait: true
    timeout: 600

  releases:
    - name: nginx-ingress
      namespace: ingress
      chart: stable/nginx-ingress
      values:
      - nginx-ingress/values.yaml

